version: '3'

services:
  redis:
    image: "redis:alpine"

  ga-worker:
    build: './ga-worker'
    depends_on:
      - redis
    volumes:
      - ./ga-worker:/code
    
    #ports:
    # - "5000:5000"
    #command: sleep infinity
    # command:  tail -F anything
    command: python main.py
    environment:
      MESSAGE_TYPE : QUEUE
  
  setup:
    build: './setup'
    depends_on:
      - redis
      - ga-worker
    volumes:
      - ./setup:/code
    command: python experiment.py
    environment:
      MESSAGE_TYPE: QUEUE


